hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:name>', views.person, name="name"),
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'hello/index.html', {
        'message': 'Hello, world!'
    })

def person(request, name):
    return render(request, 'hello/person.html', {
        'name': name.capitalize(),})

newyear/views.py
from django.shortcuts import render
from datetime import datetime
# Create your views here.

current_month = datetime.now().month
current_date = datetime.now().day

def index(request):
    return render(request, 'newyear/index.html',
                   {'current_date': current_date, 'current_month': current_month})

tasks/views.py
from django.shortcuts import render
from django import forms

class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task', max_length=100)
    priority = forms.IntegerField(label='priority', min_value=1, max_value=10)

tasks = ['Buy groceries', 'Walk the dog', 'Finish homework']
# Create your views here.
def index(request):
    return render(request, 'tasks/index.html', {'tasks': tasks})

def add(request):
    return render(request, 'tasks/add.html', {
        'form': NewTaskForm()
    })

hello/templates/hello/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>

hello/templates/hello/person.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Person</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

newyear/templates/newyear/index.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newyear</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
</head>
<body>
    {%if current_date and current_month is 1 %}
    <h1>Happy New Year!</h1>
    {%else%}
    <h1>It is not Newyear!</h1>
    {%endif%}
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Add Task</h1>
<form action="{% url 'tasks:add' %}", method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Add Task</button>
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
<a href="{% url 'tasks:add' %}">Add Tasks</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>